[tox]
envlist = begin,py3{10,11,12,13,14},end
          py3{10,11,12,13,14}-functional
          ruff,ruff-check,mypy
minversion = 2.0
skipsdist = false
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
extras =
  test
setenv =
  PACKAGE_NAME=genesis_devtools
  TEST_PATH={env:PACKAGE_NAME}/tests/unit
  functional: TEST_PATH={env:PACKAGE_NAME}/tests/functional
commands =
  coverage run -p -m pytest {posargs} --timer-top-n=10 {env:TEST_PATH}
allowlist_externals =
  markdownlint-cli2
  rm

[testenv:begin]
runner = uv-venv-lock-runner
envdir = {toxworkdir}/cover
commands =
  coverage erase

[testenv:end]
runner = uv-venv-lock-runner
envdir = {toxworkdir}/cover
commands =
  coverage combine
  coverage html -d cover
  coverage xml -o cover/coverage.xml
  coverage report --skip-covered

[testenv:ruff-check]
extras =
  ruff
runner = uv-venv-lock-runner
commands = ruff check .

[testenv:ruff]
extras =
  ruff
runner = uv-venv-lock-runner
commands =
  ruff format
  ruff check . --fix

[testenv:mypy]
extras =
  mypy
runner = uv-venv-lock-runner
commands = mypy -p genesis_devtools

[testenv:docs]
extras =
  docs
runner = uv-venv-lock-runner
commands = mkdocs serve --dev-addr 0.0.0.0:8181 --livereload

[testenv:docs-deploy]
extras =
  docs
runner = uv-venv-lock-runner
commands = mkdocs gh-deploy --force

[testenv:develop]
runner = uv-venv-lock-runner
extras =
  test
usedevelop=true

[testenv:bin]
extras =
  bin
runner = uv-venv-lock-runner
commands = pyinstaller --name genesis --recursive-copy-metadata genesis_devtools --add-data="genesis_devtools/packer/*:genesis_devtools/packer" --hidden-import=genesis_devtools.packer --add-data="genesis_devtools/repo/*:genesis_devtools/repo" --hidden-import=genesis_devtools.repo --onefile ./genesis_devtools/cmd/cli.py

[testenv:mdlint]
runner = uv-venv-lock-runner
commands = markdownlint-cli2 --config .markdownlint.yaml "**/*.md" "#node_modules" --fix

[testenv:cli_docs]
runner = uv-venv-lock-runner
setenv =
  PACKAGE_NAME=genesis_devtools
  TEST_PATH={env:PACKAGE_NAME}/tests/manual/test_cli.py
commands =
  rm -rf {env:PACKAGE_NAME}/docs/cli/*
  pytest {posargs} {env:TEST_PATH}
